### ISSUE TITLE
Validate morphisms between models of discrete double theories

### ISSUE THREAD

**Issue by epatters** [ToposInstitute/CatColab#104]
Follow-up task to #103. Validation should follow the pattern already established for graph morphisms.

**Comment by kris-brown** [comment]
I noticed there is no graph morphism validation error for having *extra data* in the map. Is this by design?

**Comment by epatters** [comment]
It's not by design; I didn't even think about it :) Now that I am thinking about it, I'm not sure whether it should be an error. Maybe it's fine? What do you think?

Also CC @olynch who has been thinking about dependent types as a relation between the base and the total type.

**Comment by kris-brown** [comment]
I'm fine either way, but it reminds me of the `@acset` macro which used to silently ignore any misspelled words, e.g. `Employe=3`. I'm also imagining programmatically generating the vectors for the components of a graph mapping and, due to some conceptual error, we're producing vectors larger than they need to be. It might be nicer to get an error of the "index error" kind than a "unnatural mapping" kind.

**Comment by epatters** [comment]
I'm persuaded by that, especially given that CatColab is supposed to be designed to give informative error messages!

**Comment by kris-brown** [comment]
I guess this only makes sense for *finitely presented* graph morphisms / model morphisms - the general interface just exposes how it acts on objects, so it wouldn't make sense to test for 'extra data'.
