### ISSUE TITLE
Backend technology survey

### ISSUE THREAD

**Issue by epatters** [ToposInstitute/CatColab#32]
At this stage, we want to keep the backend as simple as possible but we do need to get something up to enable persistence and sharing of user data. First we need to choose a backend language and server.

To avoid needless proliferation, the language should be one we are already using, namely TypeScript or Rust. But since we don't have run in the browser, it might as well be Rust, which by now has a respectable [web stack](https://www.arewewebyet.org/) with bindings for many databases.

A list of Rust HTTP server tools is [here](https://lib.rs/web-programming/http-server). The most popular is Axum, followed by Actix Web.

**Comment by olynch** [comment]
I think the main question here is whether we want to actually *do* anything mathematical on the backend, or if the backend is simply a dumb storage for documents.

If we don't want to actually do anything on the backend, then I think it makes sense to just essentially clone the node.js sync server that automerge provides (https://github.com/automerge/automerge-repo-sync-server); I don't really imagine using many features above and beyond what's already in there.

If we want to do mathematical things on the backend... then I think it *still* makes sense to use typescript because that's our only well-typed interface to automerge documents.

However, long term, once we have well-typed access to our notebooks from the Rust side, I think it will make sense to rewrite the backend in Rust (and maybe the frontend too).

**Comment by epatters** [comment]
I think that for a good while we will try to avoid doing mathematical things on the backend, pushing it all instead to Rust-wasm on the frontend. Thus, the backend will be closer to dumb storage.

Perhaps the practical strategy for the backend is the same one we're using for the frontend: choose TypeScript or Rust as is convenient and as the broader ecosystem supports. So if the automerge-repo-sync is written in TypeScript, we just go with it (and no, we should not rewrite it, however fun and educational it would be :) but that hopefully will not be forcing other decisions.

**Comment by KevinDCarlson** [comment]
As I understand it, we have since decided to do a Typescript interface with the Automerge server into a Postgres database.

**Comment by epatters** [comment]
@olynch is writing up some dev docs about the backend in #62. Let's close after that documentation is finished and merged.
