### ISSUE TITLE
Why not just Enter instead of Shift-Enter?

### ISSUE THREAD

**Issue by olynch** [ToposInstitute/CatColab#48]
In the majority of cases, cells in notebooks are single-line. The one exception is the rich text editor. We could operate like a chat client and bind "enter" to new cell, and "shift-enter" to newline, because newline is relatively rare.

**Comment by epatters** [comment]
Yeah, I had thought about this and wasn't sure what would be most intuitive. I went with Shift-Enter because

- it's the idiom that Jupyter notebooks use
- it makes the rich text and formal cells behave in a uniform way

I'm open to being persuaded to go in the other direction though.

**Comment by olynch** [comment]
I think it would be a bit frustrating to have to remember to use shift-enter in rich text cells, now that I think about it. But I think nobody would complain if enter in other cells added a new cell, in addition to shift-enter.

**Comment by epatters** [comment]
Ok, I like that. It maintains consistency while making it easier to get out of formal cells.

**Comment by KevinDCarlson** [comment]
Are we definitely sure that we don't want to allow big complicated multi-line names for, say, entities?

**Comment by epatters** [comment]
I doubt we want to allow multi-line names for entities because they'll be awkward to display in other parts of the UI, such as tab completion drop-downs (#22). I do think we'll to eventually allow entities that have their own pages/notebooks will additional description a la discourse graphs, but I don't think that affects the reasoning here.

**Comment by epatters** [comment]
Closing since I think we're happy with Shift-Enter for now.
