### ISSUE TITLE
Arrow glyphs don't display in morphism cells on Safari

### ISSUE THREAD

**Issue by KevinDCarlson** [ToposInstitute/CatColab#79]
The notebook panel doesn't display arrows for attributes/aspects/promotions/inhibitions on Safari on Mac.
![Screenshot 2024-07-30 at 5 08 18 PM](https://github.com/user-attachments/assets/de6d1b2d-464c-47dd-b82a-33feeea4126f)

**Comment by epatters** [comment]
So the issue is that there are a few places in the CSS that use [`light-dark`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) but this CSS feature in only supported the most recent versions (v17.5+) of Safari. For example, on my only slighted dated Mac, it doesn't work (Safari v17.4.1).

Since we don't yet actually have consistent support for a dark mode, we can just remove the uses of `light-dark` for now.
